### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by programacion-web** [adambutler/poll#9]
It seems that is not working to me.

Any help?

```
sudo rails server -b xx.xx.xx.xx -e production
=> Booting WEBrick
=> Rails 4.1.6 application starting in production on http://xx.xx.xx.xx:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/usr/lib/ruby/1.9.1/uri/generic.rb:213:in `initialize': the scheme http does not accept registry part: :@ (or bad hostname?) (URI::InvalidURIError)
	from /usr/lib/ruby/1.9.1/uri/http.rb:84:in `initialize'
	from /usr/lib/ruby/1.9.1/uri/common.rb:214:in `new'
	from /usr/lib/ruby/1.9.1/uri/common.rb:214:in `parse'
	from /usr/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
	from /var/lib/gems/1.9.1/gems/pusher-0.14.1/lib/pusher/client.rb:53:in `url='
	from /home/ubuntu/poll/config/initializers/pusher.rb:3:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
	from /var/lib/gems/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `block in load'
	from /var/lib/gems/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /var/lib/gems/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /var/lib/gems/1.9.1/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:647:in `load_config_initializer'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:611:in `each'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
	from /usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `each'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
	from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
	from /home/ubuntu/poll/config/environment.rb:5:in `<top (required)>'
	from /home/ubuntu/poll/config.ru:3:in `require'
	from /home/ubuntu/poll/config.ru:3:in `block in <main>'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /home/ubuntu/poll/config.ru:in `new'
	from /home/ubuntu/poll/config.ru:in `<main>'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/commands/server.rb:50:in `app'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
	from /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/commands/server.rb:69:in `start'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /var/lib/gems/1.9.1/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/ubuntu/poll/bin/rails:8:in `require'
	from /home/ubuntu/poll/bin/rails:8:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `load'
	from /var/lib/gems/1.9.1/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `call'
	from /var/lib/gems/1.9.1/gems/spring-1.1.3/lib/spring/client/command.rb:7:in `call'
	from /var/lib/gems/1.9.1/gems/spring-1.1.3/lib/spring/client.rb:26:in `run'
	from /var/lib/gems/1.9.1/gems/spring-1.1.3/bin/spring:48:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `load'
	from /var/lib/gems/1.9.1/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/ubuntu/poll/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

thans

**Comment by adambutler** [comment]
You need to have the environment variables set
